[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/modern/:splat"
  status = 200
  condition = "TypeScriptModules"

[[redirects]]
  from = "/*"
  to = "/legacy/:splat"
  status = 200